### ISSUE TITLE
FISLocationSpec

### ISSUE THREAD

**Issue by zdrossman** [learn-co-curriculum/locationTrivia-objects#1]
location property never set so there is no name to reduce to 5 characters in the test "Should shorten Location Name to 5 characters" or "Should handle negative numbers by returning the same string" or even maybe "Should return an NSString" in the describe("Shorten Location Name") block.

**Comment by jmburges** [comment]
We also need to add testing TopTrivia in the FISLocationSpec

**Comment by AnnJohn** [comment]
Iceboxing the issue.
