### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/locationTrivia-objects#4]
(a lot of this might apply to the other versions of this lab as well)

`shortenLocationName` doesn't modify anything and so should be renamed (and possibly turned into a property?)

`getLocationNamesWithLocations` .. "get" is a no-no

`verifyLocation` -> `-isValidLocation`, or a readonly property?

`searchForLocationName:inLocations:` .. not in line with Apple stuff. Probably `locationNamed:inArray:` or something

`topTrivia` -> `mostLikedTriviaQuestion`

`FISTrivia` -> `FISTriviaQuestion`?

**Comment by AnnJohn** [comment]
Iceboxing for now
